{% set name = "datasette-enrichments" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7eaa158eaa2cce3aac12a55dc6c6c42b29b22212e5b57920268c04eb18594146

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - datasette-secrets >=0.2
    - python >=3.8
    - datasette
    - wtforms

test:
  imports:
    - datasette_enrichments
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/simonw/datasette-enrichments
  summary: Tools for running enrichments against data stored in Datasette
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
