{% set name = "datasette-enrichments" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4781e020cd66efc2323eb0906cc6a9f662f76b20667c7990e1535b96d49cbf25

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - datasette-secrets >=0.2
    - python >={{ python_min }}
    - datasette
    - wtforms

test:
  imports:
    - datasette_enrichments
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/simonw/datasette-enrichments
  summary: Tools for running enrichments against data stored in Datasette
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
