{% set name = "datasette-enrichments" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datasette-enrichments-{{ version }}.tar.gz
  sha256: 76f52ea3e6ccd456f7432445936075f18769db235b07ea2e98d9d830b32b5ebb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - datasette
    - wtforms

test:
  imports:
    - datasette_enrichments
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/simonw/datasette-enrichments
  summary: Tools for running enrichments against data stored in Datasette
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
